/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kamus_bahasa;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Redho AR
 */
public class Kamus extends javax.swing.JFrame {

    private Map<String, String> kata = new HashMap<String, String>();
    
    
    /**
     * Constructor
     * Creates new form Kamus
     */
    public Kamus() {
        initComponents();
        setTitle(" Production By Redho.AR--");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taHasil = new javax.swing.JTextArea();
        btTerjemahan = new javax.swing.JButton();
        statusBar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taHasil1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taHasil2 = new javax.swing.JTextArea();
        btTerjemahan1 = new javax.swing.JButton();
        btTerjemahan2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));

        txInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txInputActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Masukkan Kata :");

        taHasil.setBackground(new java.awt.Color(0, 102, 102));
        taHasil.setColumns(20);
        taHasil.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        taHasil.setForeground(new java.awt.Color(255, 255, 255));
        taHasil.setRows(5);
        jScrollPane1.setViewportView(taHasil);

        btTerjemahan.setBackground(new java.awt.Color(51, 51, 255));
        btTerjemahan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btTerjemahan.setForeground(new java.awt.Color(255, 0, 0));
        btTerjemahan.setText("Terjemahkan");
        btTerjemahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerjemahanActionPerformed(evt);
            }
        });

        statusBar.setBackground(new java.awt.Color(0, 0, 204));
        statusBar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        statusBar.setForeground(new java.awt.Color(204, 0, 0));

        taHasil1.setBackground(new java.awt.Color(0, 102, 102));
        taHasil1.setColumns(20);
        taHasil1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        taHasil1.setForeground(new java.awt.Color(255, 255, 255));
        taHasil1.setRows(5);
        jScrollPane2.setViewportView(taHasil1);

        taHasil2.setBackground(new java.awt.Color(0, 102, 102));
        taHasil2.setColumns(20);
        taHasil2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        taHasil2.setForeground(new java.awt.Color(255, 255, 255));
        taHasil2.setRows(5);
        jScrollPane3.setViewportView(taHasil2);

        btTerjemahan1.setBackground(new java.awt.Color(51, 51, 255));
        btTerjemahan1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btTerjemahan1.setForeground(new java.awt.Color(255, 0, 0));
        btTerjemahan1.setText("Terjemahkan");
        btTerjemahan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerjemahan1ActionPerformed(evt);
            }
        });

        btTerjemahan2.setBackground(new java.awt.Color(51, 51, 255));
        btTerjemahan2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btTerjemahan2.setForeground(new java.awt.Color(255, 0, 0));
        btTerjemahan2.setText("Terjemahkan");
        btTerjemahan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerjemahan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txInput, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btTerjemahan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btTerjemahan2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btTerjemahan1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txInput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btTerjemahan)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTerjemahan1))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTerjemahan2))
                .addGap(40, 40, 40)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("tutup");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btTerjemahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerjemahanActionPerformed
        String inputText = txInput.getText();
        String inputText1 = txInput.getText();
        String inputText2 = txInput.getText();
        
        //daftar kata indonesia ke jawa
        kata.put("Aku", inputText + " = Kulo");
        kata.put("Kamu", inputText + " = Kowe");
        kata.put("Kami", inputText + " = Awakdhewe");
        kata.put("Dia", inputText + " = Deweke");
        kata.put("Ini", inputText + " = iki");
        kata.put("Itu", inputText + " = Kui");
        kata.put("Apa", inputText + " = Opo");
        kata.put("Dimana", inputText + " = Ngendi");
        kata.put("Dimana", inputText + " = Wonten Pundhi");
        kata.put("Siapa", inputText + " = Sopo");
        kata.put("Mengapa", inputText + " = Ngopo");
        
        
        //Mengecek kata yang kita inputkan
        if(kata.containsKey(inputText))
        {
            statusBar.setText("");
            taHasil.setText(kata.get(inputText));
        }
        else
        {
             taHasil.setText("");
            statusBar.setText(inputText + " *tidak Ditemukan");
        }
    }//GEN-LAST:event_btTerjemahanActionPerformed

    private void txInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txInputActionPerformed

    private void btTerjemahan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerjemahan1ActionPerformed
        // TODO add your handling code here:
        String inputText1 = txInput.getText();
        
        kata.put("Aku", inputText1 + " = Dalem");
        kata.put("Sayang", inputText1 + " = Panjenengan");
        kata.put("Kamu", inputText1 + " = Kito");
        kata.put("Dia", inputText1 + " = Piyambakipun");
        kata.put("Itu", inputText1 + " = Niku");
        kata.put("Apa", inputText1 + " = Menopo");
        kata.put("Dimana", inputText1 + " = Wonten Pundhi");
        kata.put("Siapa", inputText1 + " = Sinten");
        kata.put("Mengapa", inputText1 + " = Kadhosmenopo");
        
        if(kata.containsKey(inputText1))
        {
            statusBar.setText("");
            taHasil1.setText(kata.get(inputText1));
        }
        else
        {
             taHasil.setText("");
            statusBar.setText(inputText1 + " *tidak Ditemukan");
        }
    }//GEN-LAST:event_btTerjemahan1ActionPerformed

    private void btTerjemahan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerjemahan2ActionPerformed
        // TODO add your handling code here:
        String inputText2 = txInput.getText();
        
        kata.put("Aku", inputText2 + " = Dalem");
        kata.put("Sayang", inputText2 + " = Panjenengan");
        kata.put("Kamu", inputText2 + " = Kito");
        kata.put("Dia", inputText2 + " = Piyambakipun");
        kata.put("Itu", inputText2 + " = Niku");
        kata.put("Apa", inputText2 + " = Menopo");
        kata.put("Dimana", inputText2 + " = Wonten Pundhi");
        kata.put("Siapa", inputText2 + " = Sinten");
        kata.put("Mengapa", inputText2 + " = Kadhosmenopo");
        
        if(kata.containsKey(inputText2))
        {
            statusBar.setText("");
            taHasil2.setText(kata.get(inputText2));
        }
        else
        {
             taHasil.setText("");
            statusBar.setText(inputText2 + " *tidak Ditemukan");
        }
    }//GEN-LAST:event_btTerjemahan2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Kamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Kamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Kamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Kamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Kamus().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTerjemahan;
    private javax.swing.JButton btTerjemahan1;
    private javax.swing.JButton btTerjemahan2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel statusBar;
    private javax.swing.JTextArea taHasil;
    private javax.swing.JTextArea taHasil1;
    private javax.swing.JTextArea taHasil2;
    private javax.swing.JTextField txInput;
    // End of variables declaration//GEN-END:variables
}
